### ISSUE TITLE
是否可以加上酷狗音乐概念版跳过开屏广告呢？

### ISSUE THREAD

**Issue by BigBigBIgMan** [rong862/Splash_AD#1]
酷狗概念版，是一款非常干净的听音乐APP，非常喜欢，希望大神，能够适配

**Comment by rong862** [comment]
这个app没发现有开屏广告。

**Comment by BigBigBIgMan** [comment]
> 这个app没发现有开屏广告。

我的为什么有呢，这就尴尬了。。。。
我这以前也没有，近一个月开始出现广告的。。。。
